spring:
  profiles:
    active: dev
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/photoapp}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

file:
  storage:
    path: ${FILE_STORAGE_PATH:/app/storage}